/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;

/**
 *
 * @author JON
 */
public class TelaCoordenadores extends javax.swing.JInternalFrame {

    public TelaCoordenadores() throws SQLException {
        this.talp = new TelaAlocarProfessores();
        initComponents();
        setLocation(380, 180);
    }
    
    TelaAlocarProfessores  talp;
   
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTelaCoordenadores = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProfessor = new javax.swing.JMenu();
        menuAlocProfessor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Coordenadores");

        javax.swing.GroupLayout jdpTelaCoordenadoresLayout = new javax.swing.GroupLayout(jdpTelaCoordenadores);
        jdpTelaCoordenadores.setLayout(jdpTelaCoordenadoresLayout);
        jdpTelaCoordenadoresLayout.setHorizontalGroup(
            jdpTelaCoordenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        jdpTelaCoordenadoresLayout.setVerticalGroup(
            jdpTelaCoordenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setOpaque(false);

        menuProfessor.setText("Alocação");
        menuProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfessorActionPerformed(evt);
            }
        });

        menuAlocProfessor.setText("Professores");
        menuAlocProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlocProfessorActionPerformed(evt);
            }
        });
        menuProfessor.add(menuAlocProfessor);
        menuProfessor.add(jSeparator1);

        jMenuBar1.add(menuProfessor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaCoordenadores)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaCoordenadores)
        );

        setBounds(0, 70, 1170, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAlocProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlocProfessorActionPerformed
        if (talp.isVisible()) {
            talp.toFront();
            talp.requestFocus();
            
        } else {
            jdpTelaCoordenadores.add(talp);
            talp.setVisible(true);
        }
    }//GEN-LAST:event_menuAlocProfessorActionPerformed

    private void menuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfessorActionPerformed
        

    }//GEN-LAST:event_menuProfessorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jdpTelaCoordenadores;
    private javax.swing.JMenuItem menuAlocProfessor;
    private javax.swing.JMenu menuProfessor;
    // End of variables declaration//GEN-END:variables
}
