/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;


/**
 *
 * @author JON
 */
public class TelaPrincipal extends javax.swing.JFrame {

        
    public TelaPrincipal() throws SQLException {
        this.tc = new TelaCoordenadores();
        
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
           
    }

    TelaSecretaria ts = new TelaSecretaria();
    TelaRH trh = new TelaRH();
    TelaCoordenadores tc;
    TelaProfessor tprof = new TelaProfessor();
    TelaAluno tal = new TelaAluno();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnSecretaria = new javax.swing.JButton();
        btnRH = new javax.swing.JButton();
        btnProfessor = new javax.swing.JButton();
        btnCoordenador = new javax.swing.JButton();
        btnAluno = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Secretaria - Projeto Integrador");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnSecretaria.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        btnSecretaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Secretaria.png"))); // NOI18N
        btnSecretaria.setText("SECRETARIA");
        btnSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecretariaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSecretaria);

        btnRH.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        btnRH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/RH.png"))); // NOI18N
        btnRH.setText("RH");
        btnRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRHActionPerformed(evt);
            }
        });
        jPanel1.add(btnRH);

        btnProfessor.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        btnProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Professor.png"))); // NOI18N
        btnProfessor.setText("PROFESSOR");
        btnProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorActionPerformed(evt);
            }
        });
        jPanel1.add(btnProfessor);

        btnCoordenador.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        btnCoordenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Coordenador.png"))); // NOI18N
        btnCoordenador.setText("COORDENADOR");
        btnCoordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoordenadorActionPerformed(evt);
            }
        });
        jPanel1.add(btnCoordenador);

        btnAluno.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        btnAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Aluno.png"))); // NOI18N
        btnAluno.setText("ALUNOS");
        btnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAluno);

        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jdpPrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1376, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 701, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPrincipal)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1418, 847));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCoordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoordenadorActionPerformed
      if (tc.isVisible()) {
            tc.toFront();
            tc.requestFocus();
            
        } else {
            jdpPrincipal.add(tc);
            tc.setVisible(true);
        }
    }//GEN-LAST:event_btnCoordenadorActionPerformed

    private void btnSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecretariaActionPerformed
        if (ts.isVisible()) {
            ts.toFront();
            ts.requestFocus();
            
        } else {
            jdpPrincipal.add(ts);
            ts.setVisible(true);
        }




    }//GEN-LAST:event_btnSecretariaActionPerformed

    private void btnRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRHActionPerformed
        if (trh.isVisible()) {
            trh.toFront();
            trh.requestFocus();
            
            
        } else {
            jdpPrincipal.add(trh);
            trh.setVisible(true);
        }
    }//GEN-LAST:event_btnRHActionPerformed

    private void btnProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorActionPerformed
        if (tprof.isVisible()) {
            tprof.toFront();
            tprof.requestFocus();
            
        } else {
            jdpPrincipal.add(tprof);
            tprof.setVisible(true);
        }
    }//GEN-LAST:event_btnProfessorActionPerformed

    private void btnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoActionPerformed
        if (tal.isVisible()) {
            tal.toFront();
            tal.requestFocus();
            
        } else {
            jdpPrincipal.add(tal);
            tal.setVisible(true);
        }
    }//GEN-LAST:event_btnAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAluno;
    private javax.swing.JButton btnCoordenador;
    private javax.swing.JButton btnProfessor;
    private javax.swing.JButton btnRH;
    private javax.swing.JButton btnSecretaria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDesktopPane jdpPrincipal;
    // End of variables declaration//GEN-END:variables
}
