/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Disciplina;
import model.Turma;

/**
 *
 * @author JON
 */
public class TelaCadastraTurmas extends javax.swing.JInternalFrame {

    public TelaCadastraTurmas() {
        initComponents();
        LimparTela();
        setLocation(280, 50);
    }
    
        public void LimparTela() {
        
        txtCodigo.setText("");
        cmbDisciplina.removeAllItems();
        txtAno.setText("");
        cmbHorário.removeAllItems();
        txtSemestre.setText("");
        txtDiasDaSemana.setText("");
        DefaultTableModel dtm = (DefaultTableModel) tblTurma.getModel();
        int contlin = dtm.getRowCount();
        for (int i = 0; i < contlin; i++) {
            dtm.removeRow(0);
        }
        carregaCombo();
    }

    private void carregaCombo(){
        cmbHorário.addItem(" - - Selecione um item - - ");
        cmbHorário.addItem("Matutino");
        cmbHorário.addItem("Vespertino");
        cmbHorário.addItem("Noturno");
        buscaDisciplina("", 0);
        
    }

     public int buscaDisciplina(String nome, int id){
     String sql = "SELECT * FROM disciplina";
            ArrayList<Disciplina> disc = Disciplina.ListarDisciplinas(sql);
                        
            if (disc == null) {
                return 0;
            }

            System.out.println();
            if (disc.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhuma disciplina cadastrada");
                return 0;
            }
            int iden = 0;
            
            cmbDisciplina.addItem("- - Selecione um iten - -");
            // percorre lista e mostra todas os cursos
            for (Disciplina d : disc) {

                cmbDisciplina.addItem(d.getDisc_descricao());
                if(d.getDisc_descricao().equals(nome)){
                    iden = d.getDisc_iden();
                }
                if(d.getDisc_iden() == id){
                    txtDiasDaSemana.setText(d.getDisc_descricao());
                    return 0;
                }
                
            }
        return iden;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCruds = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jlAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jlSemestre = new javax.swing.JLabel();
        txtSemestre = new javax.swing.JTextField();
        jlHorario = new javax.swing.JLabel();
        jlDiaDaSemana = new javax.swing.JLabel();
        jlDisciplina = new javax.swing.JLabel();
        cmbDisciplina = new javax.swing.JComboBox<>();
        cmbHorário = new javax.swing.JComboBox<>();
        txtDiasDaSemana = new javax.swing.JTextField();
        jpButtons = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurma = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastrar Turmas");
        setToolTipText("");

        jpCruds.setBackground(new java.awt.Color(0, 153, 153));
        jpCruds.setOpaque(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Turma"));

        btnConsultar.setBackground(new java.awt.Color(153, 153, 153));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/busca.png"))); // NOI18N
        btnConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jlCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlCodigo.setText("Codigo");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));

        jlAno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlAno.setText("Ano");

        txtAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));

        jlSemestre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlSemestre.setText("Semestre");

        txtSemestre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSemestre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSemestre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));

        jlHorario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlHorario.setText("Horário ");

        jlDiaDaSemana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDiaDaSemana.setText("Dias da Semana");

        jlDisciplina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDisciplina.setText("Disciplina:");

        cmbDisciplina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDisciplina.setFocusCycleRoot(true);
        cmbDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDisciplinaMouseClicked(evt);
            }
        });

        cmbHorário.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbHorário.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbHorárioMouseClicked(evt);
            }
        });

        txtDiasDaSemana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiasDaSemana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlAno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlSemestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlDiaDaSemana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(313, 313, 313))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbHorário, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiasDaSemana)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbDisciplina, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                        .addComponent(txtCodigo))
                                    .addComponent(jlDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(cmbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbHorário, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDiaDaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiasDaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(4, 4, 4))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbDisciplina, cmbHorário, txtAno, txtCodigo, txtDiasDaSemana, txtSemestre});

        jpButtons.setBackground(new java.awt.Color(0, 153, 153));
        jpButtons.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpButtons.setOpaque(false);
        jpButtons.setLayout(new java.awt.GridLayout(1, 1, 0, 10));

        jPanel2.setLayout(new java.awt.GridLayout());

        btnCadastrar.setBackground(new java.awt.Color(153, 153, 153));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastrar);

        btnAlterar.setBackground(new java.awt.Color(153, 153, 153));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlterar);

        btnLimpar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpar);

        javax.swing.GroupLayout jpCrudsLayout = new javax.swing.GroupLayout(jpCruds);
        jpCruds.setLayout(jpCrudsLayout);
        jpCrudsLayout.setHorizontalGroup(
            jpCrudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCrudsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCrudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCrudsLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCrudsLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpCrudsLayout.setVerticalGroup(
            jpCrudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCrudsLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpCrudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCrudsLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCrudsLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        tblTurma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD. TURMA", "DISCIPLINA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTurmaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTurma);
        if (tblTurma.getColumnModel().getColumnCount() > 0) {
            tblTurma.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblTurma.getColumnModel().getColumn(1).setPreferredWidth(160);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpCruds, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpCruds, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(370, 5, 508, 541);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        int turm_iden = Integer.parseInt(txtCodigo.getText());
        turm_iden = Integer.parseInt(txtCodigo.getText());
        int turm_ano = Integer.parseInt(txtAno.getText());
        int turm_semestre = Integer.parseInt(txtSemestre.getText());
        String turm_horario = (String) cmbDisciplina.getSelectedItem();
        String turm_diasemana = txtDiasDaSemana.getText();
        int turm_disc_iden = buscaDisciplina((String) cmbDisciplina.getSelectedItem(), 0);

        if (Turma.AlterarTurma(turm_iden, turm_ano, turm_semestre,
                turm_horario, turm_diasemana, turm_disc_iden)) {
            JOptionPane.showMessageDialog(null, "Turma Alterada com sucesso");
            LimparTela();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao Alterar");
        }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        int turm_iden = Integer.parseInt(txtCodigo.getText());
        int turm_ano = Integer.parseInt(txtAno.getText());
        int turm_semestre = Integer.parseInt(txtSemestre.getText());
        String turm_horario = (String) cmbHorário.getSelectedItem();
        String turm_diasemana = txtDiasDaSemana.getText();
        int turm_disc_iden = buscaDisciplina((String) cmbDisciplina.getSelectedItem(), 0);

        if (Turma.CadastrarTurma(turm_iden, turm_ano, turm_semestre,
                turm_horario, turm_diasemana, turm_disc_iden)) {
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
            LimparTela();
        } else {
            JOptionPane.showMessageDialog(null, "Erro no cadastro");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblTurma.getModel();
        
        int contlin = dtm.getRowCount();
        for (int i = 0; i < contlin; i++) {
            dtm.removeRow(0);
        }
        
        String sql = "";
        if (txtCodigo.getText().equals("")) {
            sql = "SELECT * FROM turma";
            ArrayList<Turma> turma = Turma.ListarTurma(sql);
            
            if (turma == null) {
                return;
            }

            System.out.println();
            if (turma.isEmpty()) {
                
                JOptionPane.showMessageDialog(null, "Nenhuma turma cadastrado");

                return;
            }

            // percorre lista e mostra todas as contas
            //JOptionPane.showMessageDialog(null, "Carregando turma cadastradas");
            for (Turma t : turma) {

                String dados[] = new String[2];
                dados[0] = String.valueOf(t.getTurm_iden());
                buscaDisciplina("", t.getTurm_disc_iden());
                dados[1] = txtDiasDaSemana.getText();
                txtDiasDaSemana.setText("");
                cmbDisciplina.removeAllItems();
                cmbHorário.removeAllItems();
                dtm.addRow(dados);

            }
        } else {
            sql = "SELECT * FROM turma WHERE turm_iden = '" + txtCodigo.getText() + "'";
            ArrayList<Turma> turma = Turma.ListarTurma(sql);
            if (turma == null) {
                return;
            }

            System.out.println();
            if (turma.isEmpty()) {
                System.out.println(txtCodigo.getText() + ".");
                JOptionPane.showMessageDialog(null, "Nenhuma turma cadastrado");

                return;
            }
            LimparTela();
            // percorre lista e mostra todas as pessoas           
            for (Turma t : turma) {
                cmbDisciplina.removeAllItems();
                txtCodigo.setText(String.valueOf(t.getTurm_iden()));
                buscaDisciplina("", t.getTurm_disc_iden());
                cmbDisciplina.removeAllItems();
                cmbDisciplina.addItem(txtDiasDaSemana.getText());
                txtAno.setText(String.valueOf(t.getTurm_ano()));
                cmbHorário.removeAllItems();
                cmbHorário.addItem(t.getTurm_horario());
                txtSemestre.setText(String.valueOf(t.getTurm_semestre()));
                txtDiasDaSemana.setText(t.getTurm_diasemana());
                
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void tblTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTurmaMouseClicked
        
        cmbHorário.removeAllItems();
        String sql = "SELECT * FROM turma";
            ArrayList<Turma> turma = Turma.ListarTurma(sql);
            
            if (turma == null) {
                return;
            }

            System.out.println();
            if (turma.isEmpty()) {
                System.out.println(txtCodigo.getText() + ".");
                JOptionPane.showMessageDialog(null, "Nenhuma turma cadastrado");

                return;
            }
        int linhaSel = tblTurma.getSelectedRow();
        
        // percorre lista e mostra todas as contas
        
        for (Turma t : turma) {

            if (Integer.parseInt((String) tblTurma.getValueAt(linhaSel, 0)) == t.getTurm_iden()) {
                cmbDisciplina.removeAllItems();
                txtCodigo.setText(String.valueOf(t.getTurm_iden()));
                buscaDisciplina("", t.getTurm_disc_iden());
                cmbDisciplina.removeAllItems();
                cmbDisciplina.addItem(txtDiasDaSemana.getText());
                txtAno.setText(String.valueOf(t.getTurm_ano()));
                cmbHorário.removeAllItems();
                cmbHorário.addItem(t.getTurm_horario());
                txtSemestre.setText(String.valueOf(t.getTurm_semestre()));
                txtDiasDaSemana.setText(t.getTurm_diasemana());
            }
        }
    }//GEN-LAST:event_tblTurmaMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparTela();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void cmbDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDisciplinaMouseClicked
        cmbDisciplina.removeAllItems();
        buscaDisciplina("", 0);
    }//GEN-LAST:event_cmbDisciplinaMouseClicked

    private void cmbHorárioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbHorárioMouseClicked
        cmbHorário.removeAllItems();
        cmbHorário.addItem(" - - Selecione um item - - ");
        cmbHorário.addItem("Matutino");
        cmbHorário.addItem("Vespertino");
        cmbHorário.addItem("Noturno");
    }//GEN-LAST:event_cmbHorárioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbDisciplina;
    private javax.swing.JComboBox<String> cmbHorário;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlDiaDaSemana;
    private javax.swing.JLabel jlDisciplina;
    private javax.swing.JLabel jlHorario;
    private javax.swing.JLabel jlSemestre;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JPanel jpCruds;
    private javax.swing.JTable tblTurma;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDiasDaSemana;
    private javax.swing.JTextField txtSemestre;
    // End of variables declaration//GEN-END:variables
}
