/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Curso;
import model.Pessoa;
import util.OrdenacaoBolha;

/**
 *
 * @author JON
 */
public class TelaCadastraCurso extends javax.swing.JInternalFrame {

    public TelaCadastraCurso() {
        initComponents();
        limparTela();
        buscaCoordenador("");
        setLocation(330, 50);
   
    }
    
        public void limparTela() {
        
        txtCodigo.setText("");
        txtDescricao.setText("");
        cmbCoordenador.removeAllItems();
        DefaultTableModel dtm = (DefaultTableModel) tblCurso.getModel();
        int contlin = dtm.getRowCount();
        for (int i = 0; i < contlin; i++) {
            dtm.removeRow(0);
        }
            buscaCoordenador("");
    }

    
   public String buscaCoordenador(String nome){
       String sql = "SELECT * FROM pessoa WHERE pes_funcao = 'Coordenador'";
            ArrayList<Pessoa> pessoa = Pessoa.listarPessoas(sql);
            OrdenacaoBolha ob = new OrdenacaoBolha();
            ob.bolha(pessoa);
            
            if (pessoa == null) {
                return null;
            }

            System.out.println();
            if (pessoa.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhuma pessoa cadastrada");
                return null;
            }
            String iden = null;
           cmbCoordenador.removeAllItems();
           cmbCoordenador.addItem(" - - Selecione - -");
            // percorre lista e mostra todas as contas
            for (Pessoa p : pessoa) {
                cmbCoordenador.addItem(p.getPes_nome());
                if(p.getPes_nome().equals(nome)){
                    iden = p.getPes_iden();
                }
                if(p.getPes_iden().equals(nome)){
                    cmbCoordenador.removeAllItems();
                    iden = p.getPes_nome();
                }
            }
        
        return iden; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbCoordenador = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCadastra = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurso = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastrar Cursos");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Codigo");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Descrição");

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Coordenador");

        cmbCoordenador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCoordenador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cmbCoordenador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCoordenadorMouseClicked(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(153, 153, 153));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/busca.png"))); // NOI18N
        btnConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        btnCadastra.setBackground(new java.awt.Color(153, 153, 153));
        btnCadastra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastra.setText("Cadastrar");
        btnCadastra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastra);

        btnAlterar.setBackground(new java.awt.Color(153, 153, 153));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlterar);

        btnLimpar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbCoordenador, 0, 456, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbCoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRICAO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCursoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCurso);
        if (tblCurso.getColumnModel().getColumnCount() > 0) {
            tblCurso.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblCurso.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(380, 5, 497, 367);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
        int curs_iden = Integer.parseInt(txtCodigo.getText());
        String curs_descricao = txtDescricao.getText();
        String curs_coord_iden = buscaCoordenador((String) cmbCoordenador.getSelectedItem());
                    
        if (Curso.CadastrarCurso(curs_iden, curs_descricao, curs_coord_iden)) {
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
        } else {
           JOptionPane.showMessageDialog(null,"Erro no cadastro");
        }
        limparTela();
 
    }//GEN-LAST:event_btnCadastraActionPerformed

    private void tblCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCursoMouseClicked
       txtCodigo.setText("");
        txtDescricao.setText("");
        String sql = "";
        if (txtCodigo.getText().equals("")) {
            sql = "SELECT * FROM curso";
            ArrayList<Curso> curso = Curso.ListarCursos(sql);
                        
            if (curso == null) {
                return;
            }

            System.out.println();
            if (curso.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhum curso cadastrado");
                return;
            }
            int linhaSel = tblCurso.getSelectedRow();
            String coordenador = null;
            // percorre lista e mostra todas os cursos
            for (Curso c : curso) {
                if(tblCurso.getValueAt(linhaSel, 0).equals(String.valueOf(c.getCurs_iden()))){
                txtCodigo.setText(String.valueOf(c.getCurs_iden()));
                txtDescricao.setText(c.getCurs_descricao());
                coordenador = c.getCurs_coord_iden();
                }
            }
        //busca diretores cadastrados
        
         sql = "SELECT * FROM pessoa WHERE pes_iden = '" + coordenador + "'";
            ArrayList<Pessoa> pessoa = Pessoa.listarPessoas(sql);
            if (pessoa == null) {
                return;
            }
            
            System.out.println();
            if (pessoa.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhuma pessoa cadastrada");
                return;
            }
             cmbCoordenador.removeAllItems();
            // percorre lista e mostra todas as pessoas           
            for (Pessoa p : pessoa) {
                
                cmbCoordenador.addItem(p.getPes_nome());
            }
        }
    }//GEN-LAST:event_tblCursoMouseClicked

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblCurso.getModel();
        String sql = "";
        if (txtCodigo.getText().equals("")) {
            sql = "SELECT * FROM curso";
            ArrayList<Curso> curso = Curso.ListarCursos(sql);
                        
            if (curso == null) {
                return;
            }

            System.out.println();
            if (curso.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhum curso cadastrado");
                return;
            }

            // percorre lista e mostra todas os cursos
            for (Curso c : curso) {

                String dados[] = new String[2];
                dados[0] = String.valueOf(c.getCurs_iden());
                dados[1] = c.getCurs_descricao();
                dtm.addRow(dados);
            }
        } else {
             int codigo = Integer.parseInt(txtCodigo.getText());
             sql = "SELECT * FROM curso WHERE curs_iden = " + codigo; 
             ArrayList<Curso> curso = Curso.ListarCursos(sql);
            if (curso == null) {
                return;
            }

            System.out.println();
            if (curso.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhum curso cadastrado");
                return;
            }

            // percorre lista e mostra todas as pessoas           
            for (Curso c : curso) {

                txtCodigo.setText(String.valueOf(c.getCurs_iden()));
                txtDescricao.setText(c.getCurs_descricao());
                String coordenador = buscaCoordenador(c.getCurs_coord_iden());
                cmbCoordenador.removeAllItems();
                cmbCoordenador.addItem(coordenador);
  
        }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int curs_iden = Integer.parseInt(txtCodigo.getText());
        String curs_descricao = txtDescricao.getText();
        String curs_coord_iden = buscaCoordenador((String) cmbCoordenador.getSelectedItem());

                 
        if (Curso.AlterarCurso(curs_iden, curs_descricao, curs_coord_iden)) {
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Erro na inserção da nova conta");
        }
        limparTela();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void cmbCoordenadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCoordenadorMouseClicked
        buscaCoordenador("");
    }//GEN-LAST:event_cmbCoordenadorMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       limparTela();
    }//GEN-LAST:event_btnLimparActionPerformed

private ArrayList<String> matricula;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbCoordenador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCurso;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
