/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author JON
 */
public class TelaRH extends javax.swing.JInternalFrame {

    public TelaRH() {
        initComponents();
        setLocation(380, 180);
    }
    
    TelaCadastraProfessor  tcp = new TelaCadastraProfessor();
    TelaCadastraCoordenador tcc = new TelaCadastraCoordenador();
//    TelaRH trh = new TelaRH();
//    TelaSecretaria tst = new TelaSecretaria();
   
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTelaRH = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProfessor = new javax.swing.JMenu();
        menuCadProfessor = new javax.swing.JMenuItem();
        menuCoordenadores = new javax.swing.JMenuItem();
        menuRH = new javax.swing.JMenuItem();
        menuSecretaria = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Recursos Humanos - RH");

        javax.swing.GroupLayout jdpTelaRHLayout = new javax.swing.GroupLayout(jdpTelaRH);
        jdpTelaRH.setLayout(jdpTelaRHLayout);
        jdpTelaRHLayout.setHorizontalGroup(
            jdpTelaRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1154, Short.MAX_VALUE)
        );
        jdpTelaRHLayout.setVerticalGroup(
            jdpTelaRHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setOpaque(false);

        menuProfessor.setText("Cadastro");
        menuProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfessorActionPerformed(evt);
            }
        });

        menuCadProfessor.setText("Professores");
        menuCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProfessorActionPerformed(evt);
            }
        });
        menuProfessor.add(menuCadProfessor);

        menuCoordenadores.setText("Coordenadores");
        menuCoordenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCoordenadoresActionPerformed(evt);
            }
        });
        menuProfessor.add(menuCoordenadores);

        menuRH.setText("RH");
        menuRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRHActionPerformed(evt);
            }
        });
        menuProfessor.add(menuRH);

        menuSecretaria.setText("Secretaria");
        menuSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSecretariaActionPerformed(evt);
            }
        });
        menuProfessor.add(menuSecretaria);
        menuProfessor.add(jSeparator1);

        jMenuBar1.add(menuProfessor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaRH)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaRH)
        );

        setBounds(0, 70, 1170, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProfessorActionPerformed
        if (tcp.isVisible()) {
            tcp.toFront();
            tcp.requestFocus();
            
        } else {
            jdpTelaRH.add(tcp);
            tcp.setVisible(true);
        }
    }//GEN-LAST:event_menuCadProfessorActionPerformed

    private void menuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfessorActionPerformed
      
    }//GEN-LAST:event_menuProfessorActionPerformed

    private void menuCoordenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCoordenadoresActionPerformed
         if (tcc.isVisible()) {
            tcc.toFront();
            tcc.requestFocus();
            
        } else {
            jdpTelaRH.add(tcc);
            tcc.setVisible(true);
        }
    }//GEN-LAST:event_menuCoordenadoresActionPerformed

    private void menuRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRHActionPerformed
//     if (trh.isVisible()) {
//            trh.toFront();
//            trh.requestFocus();
//            
//        } else {
//            jdpTelaRH.add(trh);
//            trh.setVisible(true);
//        }
    }//GEN-LAST:event_menuRHActionPerformed

    private void menuSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSecretariaActionPerformed
//        if (tst.isVisible()) {
//            tst.toFront();
//            tst.requestFocus();
//            
//        } else {
//            jdpTelaRH.add(tst);
//            tst.setVisible(true);
//        }
    }//GEN-LAST:event_menuSecretariaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jdpTelaRH;
    private javax.swing.JMenuItem menuCadProfessor;
    private javax.swing.JMenuItem menuCoordenadores;
    private javax.swing.JMenu menuProfessor;
    private javax.swing.JMenuItem menuRH;
    private javax.swing.JMenuItem menuSecretaria;
    // End of variables declaration//GEN-END:variables
}
