/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PersistenciaAlocacao;
import control.PersistenciaDisciplina;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Disciplina;
import model.Pessoa;
import util.Fila;
import util.Lista;
import util.NoFila;
import util.NoLista;

/**
 *
 * @author JON
 */
public class TelaAlocarProfessores extends javax.swing.JInternalFrame {
  
    public TelaAlocarProfessores() throws SQLException {
        initComponents();
//        listarProfessorCB();
//        listarDisciplinaCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxProfessor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDisciplina = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButtonConfirma = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Alocar Professor");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Professor");
        jPanel1.add(jLabel1);

        jComboBoxProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jComboBoxProfessor);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Turma");
        jPanel1.add(jLabel2);

        jComboBoxDisciplina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jComboBoxDisciplina);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setMinimumSize(new java.awt.Dimension(61, 45));
        jPanel2.setPreferredSize(new java.awt.Dimension(61, 45));
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jButtonConfirma.setBackground(new java.awt.Color(153, 153, 153));
        jButtonConfirma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonConfirma.setText("Confirma");
        jButtonConfirma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        jButtonConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonConfirma);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        setBounds(360, 6, 438, 381);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaActionPerformed
        Pessoa professor = new Pessoa();
        professor = (Pessoa) jComboBoxProfessor.getSelectedItem();
        Disciplina disciplina = new Disciplina();
        disciplina = (Disciplina) jComboBoxDisciplina.getSelectedItem();
        
        try {
            PersistenciaAlocacao.alocarProfessor(professor, disciplina);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAlocarProfessores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConfirmaActionPerformed

    private void listarProfessorCB() throws SQLException {
        ArrayList<Pessoa> listaProf = PersistenciaAlocacao.listaProfessor();
        Lista lista = new Lista();
        
        for(Pessoa p : listaProf) {
            lista.insereFim(p);
        }
        
        NoLista no = lista.getInicio();
        while(no != null) {
            jComboBoxProfessor.addItem(no.getPessoaInfo());
            no = no.getProx();
        }
    }
    
    private void listarDisciplinaCB() {
        ArrayList<Disciplina> listaDisciplina = PersistenciaDisciplina.listaDisciplina("SELECT * FROM disciplina");
        Fila fila = new Fila();
        
        for(Disciplina d : listaDisciplina) {
            fila.enfileirar(d);
        }
        
        NoFila no = fila.getInicio();
        while(no != null) {
            jComboBoxDisciplina.addItem(no.getInfo());
            no = no.getProx();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirma;
    private javax.swing.JComboBox<Disciplina> jComboBoxDisciplina;
    private javax.swing.JComboBox<Pessoa> jComboBoxProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
