/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author JON
 */
public class TelaAluno extends javax.swing.JInternalFrame {

    public TelaAluno() {
        initComponents();
        setLocation(380, 180);
    }
    
    TelaAlunoConsulta  tcons = new TelaAlunoConsulta ();
   
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTelaAluno = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProfessor = new javax.swing.JMenu();
        menuCadProfessor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Aluno");

        javax.swing.GroupLayout jdpTelaAlunoLayout = new javax.swing.GroupLayout(jdpTelaAluno);
        jdpTelaAluno.setLayout(jdpTelaAlunoLayout);
        jdpTelaAlunoLayout.setHorizontalGroup(
            jdpTelaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        jdpTelaAlunoLayout.setVerticalGroup(
            jdpTelaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setOpaque(false);

        menuProfessor.setText("Consultar");
        menuProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfessorActionPerformed(evt);
            }
        });

        menuCadProfessor.setText("Avaliações");
        menuCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProfessorActionPerformed(evt);
            }
        });
        menuProfessor.add(menuCadProfessor);
        menuProfessor.add(jSeparator1);

        jMenuBar1.add(menuProfessor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaAluno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaAluno)
        );

        setBounds(0, 70, 1170, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProfessorActionPerformed
        if (tcons.isVisible()) {
            tcons.toFront();
            tcons.requestFocus();
            
        } else {
            jdpTelaAluno.add(tcons);
            tcons.setVisible(true);
        }
    }//GEN-LAST:event_menuCadProfessorActionPerformed

    private void menuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfessorActionPerformed
        

    }//GEN-LAST:event_menuProfessorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jdpTelaAluno;
    private javax.swing.JMenuItem menuCadProfessor;
    private javax.swing.JMenu menuProfessor;
    // End of variables declaration//GEN-END:variables
}
