/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;




/**
 *
 * @author admin
 */
public class TelaLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        
        initComponents();
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpdPrincipal = new javax.swing.JPanel();
        txtSenha = new javax.swing.JPasswordField();
        txtMatricula = new javax.swing.JFormattedTextField();
        lbUsuario = new javax.swing.JLabel();
        lbMatricula = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setMaximizable(true);

        jpdPrincipal.setLayout(null);
        jpdPrincipal.add(txtSenha);
        txtSenha.setBounds(200, 360, 170, 37);

        txtMatricula.setEditable(false);
        txtMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            txtMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMatricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpdPrincipal.add(txtMatricula);
        txtMatricula.setBounds(200, 290, 170, 37);

        lbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Usuarios 2.png"))); // NOI18N
        jpdPrincipal.add(lbUsuario);
        lbUsuario.setBounds(240, 130, 120, 110);

        lbMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lbMatricula.setText("Matricula:");
        jpdPrincipal.add(lbMatricula);
        lbMatricula.setBounds(200, 270, 57, 16);

        lbSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbSenha.setText("Senha:");
        jpdPrincipal.add(lbSenha);
        lbSenha.setBounds(200, 340, 41, 16);

        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/fundo2.jpg"))); // NOI18N
        jpdPrincipal.add(lbFundo);
        lbFundo.setBounds(-40, -20, 710, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpdPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpdPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpdPrincipal;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JFormattedTextField txtMatricula;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
