/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.awt.image.ImageObserver.PROPERTIES;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Diario;
import model.Disciplina;
import model.Pessoa;
import model.Turma;
import util.OrdenacaoBolha;

/**
 *
 * @author JON
 */
public class TelaEmitiDiario extends javax.swing.JInternalFrame {

    public TelaEmitiDiario() {
        initComponents();
        
        buscaDisciplina("", 0);
        setLocation(210, 40);
    }
    
    public int buscaDisciplina(String nome, int id) {
        String sql = "SELECT * FROM disciplina";
        ArrayList<Disciplina> disc = Disciplina.ListarDisciplinas(sql);

        if (disc == null) {
            return 0;
        }

        System.out.println();
        if (disc.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhuma disciplina cadastrada");
            return 0;
        }
        int iden = 0;

        cmbDisciplina.addItem("- - Selecione um iten - -");
        // percorre lista e mostra todas os cursos
        for (Disciplina d : disc) {

            cmbDisciplina.addItem(d.getDisc_descricao());
            if (d.getDisc_descricao().equals(nome)) {
                iden = d.getDisc_iden();
            }
            if (d.getDisc_iden() == id) {

                return 0;
            }

        }
        return iden;
    }

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    
    public String buscaAlunoDisciplina(String disciplina) {
        DefaultTableModel dtm = (DefaultTableModel) tblDiario.getModel();
        String sql = "select distinct * from matricula m, turma t, disciplina d, pessoa p where\n"
                + "p.pes_iden = m.matr_pes_iden and\n"
                + "m.matr_turm_iden = t.turm_iden and\n"
                + "t.turm_disc_iden = d.disc_iden and\n"
                + "d.disc_descricao = '" + disciplina + "'";

        ArrayList<Pessoa> pessoa = Pessoa.listarPessoas(sql);
        OrdenacaoBolha ob = new OrdenacaoBolha();
        ob.bolha(pessoa);
        System.out.println(pessoa.size());
        if (pessoa == null) {
            return null;
        }

        System.out.println();
        if (pessoa.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhuma pessoa cadastrada");
            return null;
        }
        String matricula = null;
        int contlin = dtm.getRowCount();
        for (int i = 0; i < contlin; i++) {
            dtm.removeRow(0);
        }
        // percorre lista e mostra todas as contas
        for (Pessoa p : pessoa) {

            String dados[] = new String[3];
            dados[0] = String.valueOf(p.getPes_iden());
            dados[1] = String.valueOf(p.getPes_nome());
            dados[2] = sdf.format( new Date( System.currentTimeMillis()));
            
            dtm.addRow(dados);
        }
        System.out.println(matricula);
        return matricula;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDiario = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbDisciplina = new javax.swing.JComboBox<>();
        btnConsulta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Emitir Diário de Turma");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setOpaque(false);

        tblDiario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MATRÍCULA", "ALUNO", "DATA", "PRESENÇA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDiario);
        if (tblDiario.getColumnModel().getColumnCount() > 0) {
            tblDiario.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblDiario.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblDiario.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblDiario.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        btnSalvar.setBackground(new java.awt.Color(153, 153, 153));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Disciplina");

        cmbDisciplina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnConsulta.setBackground(new java.awt.Color(153, 153, 153));
        btnConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/busca.png"))); // NOI18N
        btnConsulta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), java.awt.Color.black, java.awt.Color.darkGray));
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbDisciplina, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(cmbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        setBounds(380, 10, 744, 488);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        buscaAlunoDisciplina((String) cmbDisciplina.getSelectedItem());
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
     DefaultTableModel dtm = (DefaultTableModel) tblDiario.getModel();  
        int row = dtm.getRowCount();
       int col = dtm.getColumnCount();
       int presenca = 0;
       boolean bool;
       Object[][] dados =new Object[row][1];
       
       for(int i = 0;i < row; i++){
         try {
                    
             if(dtm.getValueAt(i, 3)!=null){                 
                 if(dtm.getValueAt(i, 3).equals(true)){
                     presenca = 1;
                 }else{
                     presenca = 0;
                 }
             }else{
                 presenca = 0;
             }
            
             if (Diario.cadastrarDiario(String.valueOf(dtm.getValueAt(i, 0)),
                     String.valueOf(cmbDisciplina.getSelectedItem()),
                     presenca,
                     String.valueOf(dtm.getValueAt(i, 2)))) {
                 
                 
             } else {
                 JOptionPane.showMessageDialog(null, "Erro no cadastro");
             }
         } catch (Exception ex) {
             Logger.getLogger(TelaEmitiDiario.class.getName()).log(Level.SEVERE, null, ex);
         }
         
       }
       JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbDisciplina;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDiario;
    // End of variables declaration//GEN-END:variables
}
